# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: second_heart_rate.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'second_heart_rate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17second_heart_rate.proto\"E\n\x16SecondHeartRateSection\x12\x17\n\x0fstart_timestamp\x18\x01 \x01(\x05\x12\x12\n\nheart_rate\x18\x02 \x03(\x05\";\n\x0fSecondHeartRate\x12(\n\x07section\x18\x01 \x03(\x0b\x32\x17.SecondHeartRateSectionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'second_heart_rate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SECONDHEARTRATESECTION']._serialized_start=27
  _globals['_SECONDHEARTRATESECTION']._serialized_end=96
  _globals['_SECONDHEARTRATE']._serialized_start=98
  _globals['_SECONDHEARTRATE']._serialized_end=157
# @@protoc_insertion_point(module_scope)
